### ISSUE TITLE
Server API contract change

### ISSUE THREAD

**Issue by dpitt** [in-the-keyhole/khs-convo-chat-component#8]
Would like to abstract the API call to the server more... move the AJAX call back from the API to a function callback, that can be set...  A default handler will simply perform the echo....developers can supply any handler.. the handler will be responsible for calling the server with any API and process any response type that is returned.  I applied an example below....  This means the API property would be replaced with supplying the handler function... What do you think? 

....
       this.ajaxProvider.type.prototype.postFreeText(payload)
            .then(res => {
                if (!res.ok) {
                    throw new Error();
                }
                return res.text();
            })
            .then(text => {
       
                const newMessage = {
                    Body: this.props.replyMessageHandler(text ),
                    From: this.state.theirPhoneNumber,
                    key: counter++,
                    timestamp: Date.now(),
                    To: this.state.myPhoneNumber,
                };
                this.displayMessage(newMessage, () => {
                    cb(true);
                });
            })

**Comment by stvnmntjy** [comment]
Closed with Release 2.0.0 bc4db35dc374757a194598d4cf0bd0d25c6d7bb9
